#-------------------------------
# Site Settings
title: RussianPanda Research Blog 
#logo: '/images/logo.jpg'
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://russianpanda95.github.io" # The base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# Navigation Settings
menu-settings:
  menu-items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'
    - title: 'Contact Me'
      url: '/contact/'

#-------------------------------
# Author Settings
author:
  name: RussianPanda
  avatar: '/images/15.jpg'


#-------------------------------
# Hero Settings
hero:
  title: <img src="/images/logo1.png"> 
  #description: Threat Intelligence Researcher | Threat Hunter | Content Developer | The opinions expressed within the content published here are solely my own
  description: <img src="/images/demo.gif">
  image: '/images/14.png'



#-------------------------------
# Contact Settings
contact:
  email: cyberninja956@gmail.com # Add your email for contact form
  logo: '/images/02.png'
  description: You can shoot me a message using this form if you have any questions or suggestions. # Add a description of your form
# NOTE
# Norlin theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Footer section
social:
- {icon: "fa-brands fa-linkedin", link: "https://www.linkedin.com/in/anna-p-868921105/"}
- {icon: "fa-brands fa-x-twitter", name: "Twitter", link: "https://x.com/RussianPanda9xx"}
- {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://www.instagram.com/russianpanda95/"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/RussianPanda95"}
# Example of adding a new link to the footer - {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social/"}
# Other icons can be found at https://fontawesome.com/icons


# Example of adding a new link to the footer - {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social/"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: russianpanda # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: enable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp-identifier: russianpanda.us22.list-manage.com/subscribe?u=675ada996d5aa879b806c587d&id=b8d185d6e6 # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
mailchimp-button-text: Join